server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://wucy.cq.cn:3306/hmdp?useSSL=false&serverTimezone=UTC
    username: wucy
    password: wcyshiwo@933AA
  redis:
    host: wucy.cq.cn
    port: 6379
    password: wcyshiwo@933AA
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug